name: Build Container

defaults:
  run:
    working-directory: ./app

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/csenet/clipviewer-line-proxy:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy to AWS
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'ubuntu@13.113.189.59'
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: cd clipviewer-line-proxy; git pull; docker pull ghcr.io/csenet/clipviewer-line-proxy:latest; docker-compose up -d